/*
 * generated by Xtext 2.20.0
 */
package org.example.entities;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
