/*
 * generated by Xtext 2.20.0
 */
package org.example.entities;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EntitiesStandaloneSetup extends EntitiesStandaloneSetupGenerated {

	public static void doSetup() {
		new EntitiesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
